= CloudBees action: Register a build artifact

Use this action to report to CloudBees platform that an artifact version has been created from a workflow run.
Register a build artifact to enable traceability, including if a branch and/or repository is checked out that is different from the workflow repository branch.
A unique artifact ID is output from using this action.

[NOTE]
====

Do *not* include the `register-build-artifact` action in the same job with *any* of the following actions, as the resulting run would register duplicate artifact entries to CloudBees platform.

* link:https://github.com/cloudbees-io/ecr-promote-image[Promote an image in Amazon ECR]
* link:https://github.com/cloudbees-io/s3-upload-object[Store an object on Amazon S3](if `send-artifact-info: true`)
* link:https://github.com/cloudbees-io/crane[Copy Docker images with Crane]
* link:https://github.com/cloudbees-io/helm-push[Push a Helm chart]
* link:https://github.com/cloudbees-io/jfrog-artifactory-promote-image[Promote an image from JFrog Artifactory]
* link:https://github.com/cloudbees-io/jfrog-artifactory-upload-file[Upload a file to JFrog Artifactory]
* link:https://github.com/cloudbees-io/kaniko[Build and publish Docker images with Kaniko]
====

== Inputs

[cols="15%a,10%a,30%a,45%a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `name`
| String
| Yes
| The name of the artifact reported to CloudBees platform.

| `url`
| String
| Yes
| The URL where the artifact version is located.
For example, `docker.io/myapp/myimg:1.0.0`.

| `version`
| String
| Yes
| The version of the artifact reported to CloudBees platform.

| `commit`
| String
| Only required if a different repository/branch.^<<footnote,[1]>>^
| The commit ID from the source repository.

| `commit-url`
| String
| Only required if a different repository/branch.^<<footnote,[1]>>^
| The commit URL from the source repository.

| `ref`
| String
| Only required if a different repository/branch.^<<footnote,[1]>>^
| The ref or branch of the artifact repository.

| `repository-url`
| String
| Only required if a different repository/branch.^<<footnote,[1]>>^
| The artifact repository URL.

| `digest`
| String
| No, but recommended in order to track artifact versions across repositories in the link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/workflows/artifacts#history[history].
| The hash or checksum that uniquely identifies the artifact version.

| `labels`
| String
| No
| A comma-separated list of artifact labels.

|===

[#footnote]
^[1]^ By default, CloudBees platform associates the artifact version with the code commit associated with the workflow run in the workflow's repository/branch. 
If a different commit/repository/branch has been checked out for building the artifact, specify that commit ID instead.

== Outputs

[cols="2a,1a,3a",options="header"]
.Output details
|===
| Output name
| Data type
| Description

| `artifact-id`
| String
| The unique identifier of the artifact reported to CloudBees platform.
|===


== Usage examples

=== Basic example

The following is a basic example of using the action:

[source,yaml]
----
jobs:
  register_build_artifact:
      uses: cloudbees-io/register-build-artifact@v1
      with:
        name: "myApp"
        url: "docker.io/myapp/myimg:1.0.0"
        version: "1.0.0"

----

=== Using the action output

The following example accesses the `artifact-id` value in a downstream step using the `outputs` link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/dsl-syntax/contexts[context].

[source,yaml,role="default-expanded"]
----
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Register an artifact with the platform
        id: register
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "myApp"
          url: "docker.io/myapp/myimg:1.0.0"
          version: "1.0.0"
      - name: Print output parameter artifact ID
        uses: docker://alpine:latest
        shell: sh
        run: |
          echo "artifact ID for myApp:${{ cloudbees.version }} is: ${{ steps.register.outputs.artifact-id }}"     
----

=== Using optional inputs

The following example specifies the artifact digest and labels:

[source,yaml]
----
jobs:
  register_build_artifact:
      uses: https://github.com/cloudbees-io/register-build-artifact@v1
      with:
        name: "myApp"
        version: "1.0.0"
        url: "docker.io/myapp/myimg:1.0.0"
        digest: "sha256:1234567890abcdef1234567abcdef1234"
        labels: "label1,label2"
----

=== Full workflow example

The following workflow example uses the action to register a build artifact to CloudBees platform.
Then it prints the artifact ID output parameter.

.Example platform workflow YAML file
[.collapsible]
--

[source,yaml,role="default-expanded"]
----
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
        id: checkout
      - name: Register an artifact with the platform
        uses: cloudbees-io/register-build-artifact@v1
        id: register
        with:
          name: "myApp"
          url: "docker.io/myapp/myimg:1.0.0"
          version: "1.0.0"
      - name: Print output parameter artifact ID
        uses: docker://alpine:latest
        shell: sh
        run: |
          echo "artifact ID for myApp:${{ cloudbees.version }} is: ${{ steps.register.outputs.artifact-id }}"

----
--

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform-actions/latest/[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform/latest/[CloudBees platform].
