= CloudBees action: Register a build artifact

Use this action to report to the CloudBees platform that an artifact version has been created from a workflow run.
Register a build artifact to enable traceability, including if a branch and/or repository is checked out that is different from the workflow repository branch.
A unique artifact ID is output from using this action.

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `name`
| String
| Yes
| The name of the artifact reported to the CloudBees platform.

| `url`
| String
| Yes
| The URL where the artifact version is located.
For example, `docker.io/myapp/myimg:1.0.0`.

| `version`
| String
| Yes
| The version of the artifact reported to the CloudBees platform.

| `commit`
| String
| Only required if a different repository/branch.^<<footnote,[1]>>^
| The commit ID from the source repository.

| `commit-url`
| String
| Only required if a different repository/branch.^<<footnote,[1]>>^
| The commit URL from the source repository.

| `ref`
| String
| Only required if a different repository/branch.^<<footnote,[1]>>^
| The ref or branch of the artifact repository.

| `repository-url`
| String
| Only required if a different repository/branch.^<<footnote,[1]>>^
| The artifact repository URL.

| `digest`
| String
| No, but recommended in order to track artifact versions across repositories in the link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/workflows/artifacts#history[history].
| The hash or checksum that uniquely identifies the artifact version.

| `labels`
| String
| No
| A comma-separated list of artifact labels.

|===

[#footnote]
^[1]^ By default, the CloudBees platform associates the artifact version with the code commit associated with the workflow run in the workflow's repository/branch. 
If a different commit/repository/branch has been checked out for building the artifact, specify that commit ID instead.

== Outputs

[cols="2a,1a,3a",options="header"]
.Output details
|===
| Output name
| Data type
| Description

| `artifact-id`
| String
| The unique identifier of the artifact reported to the CloudBees platform.
|===


== Usage examples

=== Basic example

The following is a basic example of using the action:

[source,yaml]
----
jobs:
  register_build_artifact:
      uses: cloudbees-io/register-build-artifact@v1
      with:
        name: "myApp"
        url: "docker.io/myapp/myimg:1.0.0"
        version: "1.0.0"

----

=== Using the action output

The following example accesses the `artifact-id` value downstream using the `outputs` link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/dsl-syntax/contexts[context].

[source,yaml,role="default-expanded"]
----
      - name: Checkout
        uses: cloudbees-io/checkout@v1
        id: checkout
      - name: Register an artifact with the platform
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "myApp"
          url: "docker.io/myapp/myimg:1.0.0"
          version: "1.0.0"
      - name: Print output parameter artifact ID
              uses: docker://alpine:latest
              shell: sh
              run: |
                echo "artifact ID for myApp:${{ cloudbees.version }} is: ${{ steps.outputs.artifact-id)}}"
----

=== Using optional inputs

The following example specifies the artifact digest and labels:

[source,yaml]
----
jobs:
  register_build_artifact:
      uses: https://github.com/cloudbees-io/register-build-artifact@v1
      with:
        name: "myApp"
        version: "1.0.0"
        url: "docker.io/myapp/myimg:1.0.0"
        digest: "sha256:1234567890abcdef1234567abcdef1234"
        labels: "label1,label2"
----

=== Full workflow example

The following workflow example uses the action to register a build artifact to the platform.
Then it link:https://github.com/cloudbees-io/register-deployed-artifact[deploys the artifact] to the Docker `test` target environment and link:https://github.com/cloudbees-io/publish-evidence-item[publishes evidence] to the platform.

.Example platform workflow YAML file
[.collapsible]
--

[source,yaml,role="default-expanded"]
----
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
jobs:
  build:
    steps:
      - name: Get source code
        uses: cloudbees-io/checkout@v1
      - id: build-go-binary
        name: Build Go binary
        uses: docker://golang:latest
        run: |
          go build -a -ldflags '-w -extldflags \"-static\"'
        env:
          CGO_ENABLED: "0"
          GOOS: linux
          GOARCH: amd64

      - id: authenticate-ghcr
        name: Authenticate to GitHub cloud repository
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ghcr.io
          username: MyUsername
          password: ${{ secrets.MY_PAT }}

      - id: build-container
        name: Build container image
        uses: cloudbees-io/kaniko@v1
        with:
          dockerfile: Dockerfile
          destination: ghcr.io/MyUsername/myImage:latest

      - name: Register build artifacts
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: MyImage
          version: 1.0.0
          url: "ghcr.io/MyUsername/myImage:latest"
          repository-url: ${{ steps.checkout.outputs.repository-url }}
          commit: ${{ steps.checkout.outputs.commit }}
          commit-url: ${{ steps.checkout.outputs.commit-url }}
          ref: ${{ steps.checkout.outputs.ref }}
          labels: "for testing, not-production"
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: MyImage
          version: ${{ cloudbees.version }}
          url: ghcr.io/MyUsername/myImage:${{ cloudbees.version }}
          target-environment: test
    needs: build
  publish-evidence:
    steps:
      - name: Publish evidence
        with:
          content: This is evidence
        uses: cloudbees-io/publish-evidence-item@v1
    needs: deploy

----
--

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform-actions/latest/[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform/latest/[the CloudBees platform].
