apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterBuildArtifact
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "rtFactRegister"
          version: "1.0.0"
          url: "docker.io/myapp/myimg:1.0.0"
          digest: "sha256:5e0687d9471728b0a200e0a3840fa16466150c58f628dc6e6c40a9b07e3b3609"
          labels: "Enter,     your labels,here!    , Thanks."
          commit_id: "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0"
          repository_url: "https://github.com/cloudbees-io/checkout"
          ref: "refs/heads/main"
      - name: Artifact Id output
        uses: cloudbees-io/register-build-artifact@v1